apiVersion: v1
kind: Service
metadata:
  name: tcp-proxy-pod-autoscaler-svc
  namespace: webapp
  labels:
    app.kubernetes.io/name: tcp-proxy-pod-autoscaler    
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app.kubernetes.io/name: tcp-proxy-pod-autoscaler
