apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tcp-proxy-pod-autoscaler-sa-role-binding
  namespace: webapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tcp-proxy-pod-autoscaler-sa-role
subjects:
  - kind: ServiceAccount
    name: tcp-proxy-pod-autoscaler-sa
