apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tcp-proxy-pod-autoscaler-sa-role
  namespace: webapp
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/scale
    verbs:
      - patch
      - update
  - apiGroups:
      - ''
    resources:
      - endpoints
    verbs:
      - get
      - list
      - watch
